language: objective-c
script:
  - xctool -workspace SodexoMenuApp.xcworkspace -scheme SodexoMenuApp -sdk iphonesiumlator
  - xctool test -workspace SodexoMenuApp.xcworkspace -scheme SodexoMenuAppExampleTests -sdk iphonesiumlator
